### ISSUE TITLE
Workflow failure does not allow retry.

### ISSUE THREAD

**Issue by erikng** [grahamgilbert/imagr#64] opened 2015-05-01 17:48 UTC
If Imagr fails to pull down any component of the workflow, you do not have the ability to retry. You can hit "OK" Which will then bring up Startup Disk. Imagr is blank and only allows you to quit. Quitting Imagr (when using AutoNBI) causes it to load the normal recovery.

**Comment by grahamgilbert** [comment] 2015-05-01 17:52
This is largely by design. The only improvement I can think of would be to disable the quit item so the app can't be quit without restarting. What failures would a retry solve? The only ones I can think of are:
- 404 for image or package
- pre boot script or package install failure
- restore failure (which admittedly might be a temporary network problem, but I think that's an edge case).

**Comment by natewalck** [comment] 2015-05-01 17:54
Imagr doesn't allow you to continue unless there is already a partition present, so that averts local disk issues, correct?

@grahamgilbert, I assume your thinking is that if the workflow fails, then it was not crafted well? As in, if a workflow fails, you shouldn't fiddle with things locally until it works, you should fix the workflow.

**Comment by erikng** [comment] 2015-05-01 17:58
By "retry" I mean allowing someone to pick a workflow again, not retry from the current location.

When DeployStudio fails, you are allowed to quit or continue. Continue takes you back to the workflow area to reselect.

**Comment by natewalck** [comment] 2015-05-01 17:58
I think the question is...if the workflow fails once, when would running it again have a different outcome?

**Comment by erikng** [comment] 2015-05-01 17:59
When it's been fixed and I "refresh workflows" with the new button.

**Comment by natewalck** [comment] 2015-05-01 18:00
Ah, I see. So instead of bailing the whole app, bail back to the selector.

**Comment by erikng** [comment] 2015-05-01 18:01
Exactly. :)

**Comment by grahamgilbert** [comment] 2015-05-01 18:08
At the moment, there's one kind of failure - one that results in the error modal. It seems like we need two kinds of failure. Hard failures where nothing can continue (no config plist etc) and those that can dump you back to the select workflow screen.

**Comment by gmarnin** [comment] 2015-05-12 14:15
I ran into this today. I had a mistake in my image_config.plist which I fixed but was unable to click on refresh workflows because it was grey out.

**Comment by grahamgilbert** [comment] 2015-05-13 09:34
Fixed in https://github.com/grahamgilbert/imagr/commit/55ba85667ac2b9a8a7bc0fdfd17589464ba8c6f4

**Closed as completed by grahamgilbert** 2015-05-13 09:34 UTC
