### ISSUE TITLE
Duplicate Workflow Names do not show up

### ISSUE THREAD

**Issue by erikng** [grahamgilbert/imagr#76] opened 2015-05-12 19:34 UTC
This should be obvious since we aren't using UIDs, but if the name is equal to another, only one shows up.

**Comment by grahamgilbert** [comment] 2015-05-13 07:21
This is by design. Can be fixed by updating documentation and by solving issue #33.

**Comment by grahamgilbert** [comment] 2015-05-13 15:01
This will now be caught before the NBI is made.

**Closed as completed by grahamgilbert** 2015-05-13 15:01 UTC

**Comment by erikng** [comment] 2015-05-13 15:04
Devil's advocate here. 

This will work during rapid development stage, but once stable, an (new/drunk) admin may still cause this issue.

**Comment by gregneagle** [comment] 2015-05-13 15:59
A new/drunk admin can cause all sorts of issues. If you rely on some other key to id workflows, a new/drunk or even old/sober admin can still screw that up as well.

**Comment by grahamgilbert** [comment] 2015-05-13 16:04
_Something_ has to be unique, it might as well be the name. The validation tool will still be there, and is included in the DMG as well as the git repo.
