### ISSUE TITLE
Cloning Error when dmg url is incorrect

### ISSUE THREAD

**Issue by erikng** [grahamgilbert/imagr#75] opened 2015-05-12 19:34 UTC
Imagr will present a cloning error dialog, which you can hit OK to and then reboot/select startup disk

Imagr should take you back to the workflow selection (this is similar to https://github.com/grahamgilbert/imagr/issues/64 )

**Comment by grahamgilbert** [comment] 2015-05-13 07:25
This is a duplicate of issue #64

**Closed as completed** 2015-05-13 07:25 UTC
